apiVersion: v1
kind: Service
metadata:
  name: {{ include "budgetelier.fullname" . }}
spec:
  selector:
    app: budgetelier
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 5000