apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgetelier
  labels:
    app: budgetelier
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: budgetelier
  template:
    metadata:
      labels:
        app: budgetelier
    spec:
      containers:
      - name: budgetelier
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: 5000
        env:
        - name: DB_PATH
          value: /data/budgetelier.db
        volumeMounts:
        - name: "{{ (index .Values.volumes 0).name }}"
          mountPath: "{{ (index .Values.volumeMounts 0).mountPath }}"
        readinessProbe:
          httpGet:
            path: "{{ .Values.readinessProbe.httpGet.path }}"
            port: {{ .Values.readinessProbe.httpGet.port }}
      volumes:
      - name: "{{ (index .Values.volumes 0).name }}"
        persistentVolumeClaim:
          claimName: "{{ (index .Values.volumes 0).persistentVolumeClaim.claimName }}"